import { Theme } from './types'

export const baseLightTheme: Theme = {
    background: '#FFF7FF',
    onBackground: '#1D1A20',
    container: '#F3EBF3',
    onContainer: '#1D1A20',
    surfaceVariant: '#F9F1F9',
    onSurfaceVariant: '#4A454E',
    outline: '#7B757F',
    primary: '#6C538B',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EEDBFF',
    onPrimaryContainer: '#543B72',
    secondary: '#EFDBFF',
    onSecondary: '#6D538B',
    secondaryContainer: '#EFDBFF',
    onSecondaryContainer: '#543B72',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    warning: '#8C4F26',
    onWarning: '#FFFFFF',
    warningContainer: '#FFDBC8',
    onWarningContainer: '#6F3811',
    success: '#37693D',
    onSuccess: '#FFFFFF',
    successContainer: '#B9F0B8',
    onSuccessContainer: '#1F5027',
}

export const baseDarkTheme: Theme = {
    background: '#151218',
    onBackground: '#E8E0E8',
    container: '#2C292F',
    onContainer: '#E8E0E8',
    surfaceVariant: '#1D1A20',
    onSurfaceVariant: '#CCC4CF',
    outline: '#958E98',
    primary: '#D8BAFA',
    onPrimary: '#3C245A',
    primaryContainer: '#543B72',
    onPrimaryContainer: '#EEDBFF',
    secondary: '#543B72',
    onSecondary: '#D9BAFA',
    secondaryContainer: '#543B72',
    onSecondaryContainer: '#EFDBFF',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    warning: '#FFB68B',
    onWarning: '#522300',
    warningContainer: '#6F3811',
    onWarningContainer: '#FFDBC8',
    success: '#9DD49E',
    onSuccess: '#033912',
    successContainer: '#1F5027',
    onSuccessContainer: '#B9F0B8',
}
